#!/bin/bash

if [ "$(ls -A $MOUNTED_REPOSITORY_DIR)" ]; then
     # is not Empty
     rm -rf $WSO2IS_HOME_REPOSITORY
else
     # is Empty
     mv -f $WSO2IS_HOME_REPOSITORY/* $MOUNTED_REPOSITORY_DIR/
     rm -rf $WSO2IS_HOME_REPOSITORY
fi

ln -s $MOUNTED_REPOSITORY_DIR $WSO2IS_HOME_REPOSITORY

sh $WSO2IS_HOME/bin/wso2server.sh
