#!/bin/bash

if [ "$(ls -A $MOUNTED_REPOSITORY_DIR)" ]; then
     # is not Empty
     rm -rf $WSO2IS_HOME_REPOSITORY
else
     # is Empty
     for f in $WSO2IS_HOME_REPOSITORY/* ; do mv $f $MOUNTED_REPOSITORY_DIR ; done
     rm -rf $WSO2IS_HOME_REPOSITORY
fi

ln -s $MOUNTED_REPOSITORY_DIR $WSO2IS_HOME_REPOSITORY

sh $WSO2IS_HOME/bin/wso2server.sh
